### PR TITLE
UpdatedReadme.adoc

### PR DESCRIPTION
**Pull request by gitdeva**
I tried following the steps given but could not successfully execute the project using IntelliJ Community Edition 2016. So, when I started experimenting, found that for this example to work as expected, I had to choose "Use gradle wrapper task configuration" without which the gradle.wrapper.properties file and gradle-wrapper.jar are not created. As I am new to Spring and IntelliJ, kindly let me know if I am not making much sense. Thanks.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gitdeva Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-intellij-idea&pullRequestId=2)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-intellij-idea&pullRequestId=2) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by ryanjbaxter** [comment]
Which project specifically were you trying to import where you had the problem?

**Comment by gitdeva** [comment]
I was not importing the project but rather trying to create a new spring
mvc project with gradle using Intellij. That is where I had to choose this
option.

**Comment by ryanjbaxter** [comment]
This guide walks you through importing an existing project into IntelliJ.  If you want to create a new project you can check out the [Spring Initializr](http://start.spring.io/) and then follow this guide to import that project.

**Comment by gregturn** [comment]
Agree with @ryanjbaxter. IntelliJ has a "New Project" option which takes you through a series of prompts that uses the Spring Initializr under the hood, and you also get the Gradle wrapper bits as well.

Now I seem to remember IntelliJ not configuring itself for a Gradle project to actually use the Gradle wrapper that start.spring.io supplies you with. If that is truly the case (never used Community Edition myself), at that point, you can re-import the project you just created, and be sure to pick  "Use included Gradle wrapper" (or whatever the exact text is). 

P.S. Make sure you pick the right version of Java. I have both Java 7 and 8 on my Mac, and IntelliJ ALWAYS picks Java 7, so I have to tell it on the import screens to pick Java 8 for Gradle.

**Comment by gitdeva** [comment]
Yes, I did choose Java 8 when creating a project. Thanks a lot @ryanjbaxter
& Greg for clarifying things.

**Pull request closed without merging**
